<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    
</body>
</html>
<script>
          // function Fn(){

      // }
      // Fn.call//apply//bind//prototype
      //函数当作对象使用时称为函数对象
// ------------------------------------------------
//回调函数 自己定义 没有调用 执行了
      //同步回调，异步回调
//forEach里面的()=>{}//是同步回调函数
 //     [1,2,3].forEach(()=>{})
//setTimeout里面的()=>{}//是异步回调函数
      // setTimeout(()=>{

      // },0)

// ------------------------------------------------

// js error处理
// 常见内置错误
//Error 所有错误的父类型 throw new Error()的类型

// 1，ReferenceError  引用的变量不存在
// console.log(a) 没有捕获error 下面代码不会执行

// 2，TypeError  数据类型错误
// let b=null;
// console.log(b.xxx)

// 3，RangeError数据值不在其允许的范围内
// function fn(){
//   fn()
// }
// fn()

// 4，SyntaxError 语法错误
// const a=''''

// ------------------------------------------------

//错误处理 
    // 捕获错误 try catch
    // 抛出错误 throw error

    // try{//有可能出现问题的代码放在try里，一旦出现错误用catch捕获
    //   let d;
    //   console.log(d.xxx)
    // }catch(error){
    //   console.log(error.message)
    //   console.log(error.stack)
    // }


// //自己抛出错误
// function someting(){
//   if(new Date()%2==1){
//     console.log('当前时间奇数，正常执行')
//   }else{//由调用者处理
//     throw new Error('当前时间为偶数')
//   }
// }

// try{
//   someting()
// }catch(error){
// alert(error.message)
// }

// 同步回调 异步回调  自己定义的 没有调用 执行了

// promise.then 指定回调函数可以在任何时候 



//-------------------------------------------------------------------
// 关键问题1
//如何改变promise的状态
// 1，resolve(value),pending变为resolved
// 2，reject(reason),pending变为rejected
// 2，抛出异常，如果当前是pending就变为rejected

// const p=new Promise((resolve,reject)=>{
//   // throw new Error('xixi')//抛出异常 promise变为rejected，reason为throw的error
//   throw 3 //抛出异常 promise变为rejected，reason为throw的3
//   // console.log(op)
// })
// p.then(
//   value=>{
//     console.log('onResolve',value)
//   },
//   reason=>{
//     console.log('onRejecttttttttttttt',reason)
//   }
// )



//关键问题2
// 一个promise指定多个成功/失败回调函数，都会调用
// const p=new Promise((resolve,reject)=>{
//   throw 3 
// })
// p.then(
//   value=>{
//     console.log('onResolve1',value)
//   },
//   reason=>{
//     console.log('onReject1',reason)
//   }
// )
// p.then(
//    value=>{
//     console.log('onResolve1',value)
//   },
//   reason=>{
//     console.log('onReject2',reason)
//   }
// )

//关键问题3
//改变promise状态和指定回调函数，谁先谁后
//1，都有可能，正常是先指定回调函数，在改变状态
//2，如何先改变状态在指定回调函数
    // a，在执行器中直接调用resolve()/reject()
    // b，延迟更长时间才指定then
//3，什么时候才能得到数据

// const p=new Promise((resolve,reject)=>{
//   setTimeout(()=>{
//     resolve(1)//后改变状态(同时指定数据),异步执行回调函数
//   },1000)
// })
// p.then(//先指定回调函数,保存当前指定的回调函数
//   value=>{
//     console.log('onResolve1',value)
//   }
// )

// //如何先改变状态在指定回调函数
// // 1,// resolve(1)和 p.then是同步执行  p.then(里面的函数是异步的)
// const p=new Promise((resolve,reject)=>{
//     resolve(1)//先改变状态(同时指定数据),
// })
// p.then(//后指定回调函数,异步执行回调函数
//   value=>{
//     console.log('onResolve1',value)
//   }
// )
// //2,
// const p=new Promise((resolve,reject)=>{
//       setTimeout(()=>{
//         resolve(1)//后改变状态(同时指定数据),异步执行回调函数
//       },1000)
// })
// setTimeout(()=>{
//   p.then(//后指定回调函数,异步执行回调函数
//     value=>{
//       console.log('onResolve1',value)
//     }
//   )
// },1100)

//4,关键问题
//promise.then()返回的新promise的结果状态由then()指定的回调函数执行的结果决定
// 1,如果抛出异常,新promise变为rejected,reason为抛出的异常,
// 2,如果返回的是非promise的任意值,新promise变为resolved,value为返回的值
// 3,如果返回的是另一个新的promise,此promise的结果就会成为新promise的结果

// new Promise((resolve,reject)=>{
//     resolve(1)
// }).then(
//   value=>{
//     console.log('onResolved1',value);
//     // return 2;
//     // return new Promise((resolve,reject)=>{
//     //   resolve(3)
//     // })
//     // return Promise.reject(4);
//     throw 5
//   },
//   reason=>{
//     console.log('onRejected1',value)
//   }
// ).then(
//   value=>{
//     console.log('onResolved2',value)
//   },
//   reason=>{
//     console.log('onRejected2',reason)
//   }
// )

//关键问题5 
//promise如何串联多个操作任务
//1，promise的then()返回一个新的promise，可以开then()的链式调用
//2，通过then()的链式调用串联多个同步/异步任务
// new Promise((resolve,reject)=>{
//     setTimeout(()=>{
//       console.log('执行任务1（异步）')
//       resolve(1)
//     },1000)
// }).then(
//   value=>{
//    console.log('任务1结果',value);
//    console.log('执行任务2（同步）');
//    return 2;
//         // resolve(2),不能这样写，，，，resolve(2)只能写在执行器中
//   }
// ).then(
//   value=>{
//       console.log('任务2结果',value);
//       console.log('执行任务3（异步）');
//       // setTimeout(()=>{//不行
//       //   return 3
//       // },1000)
//       return new Promise((resolve,reject)=>{
//         setTimeout(()=>{
//           resolve(3)
//         },1000)
//       })
//   },
// ).then(
//   value=>{
//     console.log('任务3结果',value);
//   },
//     reason=>{
//     console.log('任务3结果失败',reason)
//   }
// )



// new Promise((resolve,reject)=>{
//    reject(1)
// }).then(
//   value=>{
 
//   },
//   reason=>{
//     console.log('reason1',reason);
//     //相当于 return undefined
//   }
// ).then(
//   value=>{
//     console.log(value)
//   },
//   reason=>{

//   }
// )


//关键问题
//6，promise的异常传/穿透；
//当使用promise的then链式调用时，可以在最后指定失败的回调，前面任何操作出了异常都会传到最后失败的回调中处理
//7，中断promise链；
//当使用promise的then链式调用时，在中间中断，不再调用后面的回调函数，
//办法：在回调函数中返回一个pending状态的promise

// new Promise((resolve,reject)=>{
//   //  resolve(1)
//   reject(1)
// }).then(
//   value=>{
//     console.log('onresolved1',value);
//     return 2;
//   },
//   // reason=>{return Promise.reject(reason)}
//   // reason=> {throw reason}  不写 这里相当于写了reason=> {throw reason}
//   //或者reason=>{return Promise.reject(reason)}
//   //=> 右面没有紧跟着{}时有return的作用    throw的左边不能return
//   //
// ).then(
//   value=>{
//     console.log('onresolved2',value);
//     return 3;
//   },
//   // reason=> {throw reason} 
// ).then(
//   value=>{
//     console.log('onresolved3',value);
//   },
//   // reason=> {throw reason} 
// ).catch(//catch 也返回一个新的promise 
//   reason=>{
//         console.log('onrejected1111',reason);
//         //相当于return undefined

//         //如果下面的then想走reason，
//         //可以1，throw reason，
//         //2 return Promise.reject(reason);------没有return还是相当于return undefined

//         //如果想在此中断，不进入下面的then
//         return new Promise(()=>{})//返回一个pending的promise

//   }
// ).then(
//    value=>{
//         console.log('aaaaaaaa',value);
//   },
//    reason=>{
//         console.log('bbbbbbbb',reason);
//   }
// )

</script>